### ISSUE TITLE
前端工程师深学node或者go哪个对于职业发展提升大

### ISSUE THREAD

**Issue by genalhuang** [keelii/vim-snippets#1]

**Comment by genalhuang** [comment]
本人前端小白，请教前辈职业发展意见

**Comment by keelii** [comment]
@genaller GO 我不会，也不敢说。但我是不建议所谓的深入的学 node 的，node 会用就行了。

既然你说的是职业发展，那么有一个更重要的问题就是：

> 你打算人事前端多久？或者说计划编程多久？

如果是3，5年那么学习两门语言是没问题的。如果是更长的计划，我相信学完两三门语言后你就可以真正的**深入**一门语言或者说一个领域了

到那时候语言已经不再是你的障碍，更多的是一些语言无关的知识：操作系统、网络通信、加密解密、图形图像。这每一个领域都值得你深入学习。而且可以深入学习几年十年，甚至更久。

说了这么多简单一句话总结：先学 java 入门，因为这是一门你即可以入门又可以开阔视野，还极有生产力的语言。学会了 java 你可以找到工作，衣食方可足，荣辱才可知，之后成就是成就你个人理想的时候了。

**Comment by genalhuang** [comment]
感谢你的耐心解答，我今年毕业，打算整个职业生涯都编程，也感谢你的建议哈哈，我想我会好好考虑java的学习的。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "kily zhou"<notifications@github.com&gt;; 
发送时间: 2020年4月29日(星期三) 晚上8:12
收件人: "keelii/vim-snippets"<vim-snippets@noreply.github.com&gt;; 
抄送: "磁带机"<3505563308@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [keelii/vim-snippets] 前端工程师深学node或者go哪个对于职业发展提升大 (#1)





 
@genaller GO 我不会，也不敢说。但我是不建议所谓的深入的学 node 的，node 会用就行了。
 
既然你说的是职业发展，那么有一个更重要的问题就是：
  
你打算人事前端多久？或者说计划编程多久？
  
如果是3，5年那么学习两门语言是没问题的。如果是更长的计划，我相信学完两三门语言后你就可以真正的深入一门语言或者说一个领域了
 
到那时候语言已经不再是你的障碍，更多的是一些语言无关的知识：操作系统、网络通信、加密解密、图形图像。这每一个领域都值得你深入学习。而且可以深入学习几年十年，甚至更久。
 
说了这么多简单一句话总结：先学 java 入门，因为这是一门你即可以入门又可以开阔视野，还极有生产力的语言。学会了 java 你可以找到工作，衣食方可足，荣辱才可知，之后成就是成就你个人理想的时候了。
